version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: "llm_engineering_mongo"
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: "llm_engineering"
      MONGO_INITDB_ROOT_PASSWORD: "llm_engineering"
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - local
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: "llm_engineering_qdrant"
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - local
    restart: always

  app:
    build: ./app
    container_name: "llm_engineering_app"
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      - local
    depends_on:
      - mongo
      - qdrant

  clearml:
    image: allegroai/clearml:latest
    container_name: "llm_engineering_clearml"
    ports:
      - 8080:8080
    environment:
      CLEARML_API_ACCESS_KEY: "your_access_key"
      CLEARML_API_SECRET_KEY: "your_secret_key"
      CLEARML_WEB_HOST: "http://localhost:8080"
      CLEARML_API_HOST: "http://localhost:8080"
      CLEARML_FILES_HOST: "http://localhost:8080"
    volumes:
      - clearml_data:/root/.clearml
    networks:
      - local
    restart: always

volumes:
  mongo_data:
  qdrant_data:
  clearml_data:

networks:
  local:
    driver: bridge
